// <auto-generated />
using System;
using BloodDonation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonation.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711140948_AddBloodTypeAndAppointmentLink")]
    partial class AddBloodTypeAndAppointmentLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BloodDonation.API.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BloodDonation.API.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedByAdminId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("BloodDonation.API.Models.DonationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityQuestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Hematocrit")
                        .HasColumnType("REAL");

                    b.Property<double>("Hemoglobin")
                        .HasColumnType("REAL");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PregnancyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentIllness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurgeryHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("DonationForms");
                });

            modelBuilder.Entity("BloodDonation.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BloodDonation.API.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DonorsNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 48,
                            BloodType = "",
                            ContactInfo = "",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 9, 48, 148, DateTimeKind.Utc).AddTicks(914),
                            Description = "Help us restore critical blood reserves. Join the national drive at Al-Hussein Park.",
                            DonorsNeeded = 0,
                            EndDateTime = new DateTime(2026, 7, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Al-Hussein Park, Amman",
                            MaxCapacity = 50,
                            StartDateTime = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Title = "Amman Central Blood Drive",
                            Type = "Event",
                            UrgencyLevel = ""
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 30,
                            BloodType = "",
                            ContactInfo = "",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 9, 48, 148, DateTimeKind.Utc).AddTicks(1166),
                            Description = "Your blood donation can save three lives. Come and contribute.",
                            DonorsNeeded = 0,
                            EndDateTime = new DateTime(2026, 7, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Location = "King Abdullah II Gardens, Irbid",
                            MaxCapacity = 30,
                            StartDateTime = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Title = "Irbid Community Donation Event",
                            Type = "Event",
                            UrgencyLevel = ""
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 0,
                            BloodType = "O-",
                            ContactInfo = "0790000001",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 9, 48, 148, DateTimeKind.Utc).AddTicks(2335),
                            Description = "A patient is undergoing open-heart bypass surgery and requires immediate O- negative blood donations.",
                            DonorsNeeded = 3,
                            ExpiryTime = new DateTime(2026, 7, 10, 23, 59, 59, 0, DateTimeKind.Utc),
                            Location = "Specialty Hospital, Amman",
                            MaxCapacity = 0,
                            Status = "Active",
                            Title = "Urgent O- Required at Specialty Hospital",
                            Type = "Emergency",
                            UrgencyLevel = "Emergency"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 0,
                            BloodType = "A+",
                            ContactInfo = "0790000002",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 9, 48, 148, DateTimeKind.Utc).AddTicks(2339),
                            Description = "Platelet donation needed for a leukemia patient undergoing chemotherapy at KHCC.",
                            DonorsNeeded = 5,
                            ExpiryTime = new DateTime(2026, 7, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Location = "King Hussein Cancer Center, Amman",
                            MaxCapacity = 0,
                            Status = "Active",
                            Title = "A+ Donors Needed for Leukemia Patient",
                            Type = "Emergency",
                            UrgencyLevel = "High"
                        });
                });

            modelBuilder.Entity("BloodDonation.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EligibilityExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodType = "",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = "1990-01-01",
                            EligibilityStatus = "Eligible",
                            Email = "admin@blood.jo",
                            FullName = "National Blood Bank Admin",
                            Gender = "Male",
                            MobileNumber = "0791234567",
                            NationalId = "9901020304",
                            Nationality = "Jordanian",
                            PasswordHash = "342IHFCmkWx+4Auu8lDJhQoxcv3QA/pfVNsGeKqEGFo=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("BloodDonation.API.Models.Appointment", b =>
                {
                    b.HasOne("BloodDonation.API.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.API.Models.Attendance", b =>
                {
                    b.HasOne("BloodDonation.API.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BloodDonation.API.Models.DonationForm", b =>
                {
                    b.HasOne("BloodDonation.API.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("BloodDonation.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.API.Models.Notification", b =>
                {
                    b.HasOne("BloodDonation.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
